#!/usr/bin/env bash

# ***This script was made by Clay Gomera (Drake)***
#  - Description: A simple desktop dmenu script
#  - Dependencies: dmenu, j4-dmenu-desktop

DMENU="dmenu -l 10 -b -i -p Launch:"
j4-dmenu-desktop --dmenu "$DMENU" --no-generic
