#!/usr/bin/env bash

brt=$(xbacklight -get)
if [ "$brt" = "100.000000" ]; then
    icon=🔆
elif [ "$brt" \> "50%.*" ]; then
    icon=🔆
elif [ "$brt" \< "49%.*" ]; then
    icon=🔅
fi
echo " $icon ${brt%.*}% "
